---
title: "Homework 5"
author: "Lorraine Kwok"
date: "November 5, 2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(10)
```

## Problem 1

The following code chunk generates missing values in the `iris_with_missing` dataframe.

```{r}
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

The following code chunk shows a function that will replace the missing values in each variable. For numeric variables, the missing values will be replaced with column mean. For character variables, the  

```{r}
output = vector("list", length = 5)

iris_filling = function(x) {
  
  if (is.numeric(x)) {
    x = replace_na(x, mean(x, na.rm = TRUE))
  }
  else if (is.character(x)) {
    x = replace_na(x, "virginica")
  }
  
}

output = map(iris_with_missing, iris_filling)
```

## Problem 2

```{r}
df = list.files(pattern = "*.csv")

vec_file = str_c(df)
```

```{r}

for (i in length(df):1) {
  output[[i]] = read_csv(vec_file[[i]])
}

output = map_df(vec_file, read_csv)
```

## Problem 3

